### PR TITLE
add: block arrival timestamps from monitoring at KIT

### PR DESCRIPTION
**Pull request by matthias-g**
This adds the data from the three nodes of the [Bitcoin Monitoring at KIT](https://www.dsn.kastel.kit.edu/bitcoin/) to `timestamps.csv`. The data ranges from block 369715 to 819921.

I did some basic cleaning to remove timestamps of blocks that were received late because the monitoring node was not running when the block was created.

I had to compress timestamps.csv to stay below GitHub's file size limit.

### CODE REVIEW

**Comment by 0xB10C** [comment]
Thanks! I'll have a closer look next week.

> I did some basic cleaning to remove timestamps of blocks that were received late because the monitoring node was not running when the block was created.

Awesome, I do have a quality assurance CI job that does something similar.

> I had to compress timestamps.csv to stay below GitHub's file size limit.

Hm, yeah I didn't think about this before. Maybe moving to a different format might help. For example, we don't need the header hash for each node. I'll see what I can come up with.

**Comment by 0xB10C** [comment]
> > I did some basic cleaning to remove timestamps of blocks that were received late because the monitoring node was not running when the block was created.
> 
> Awesome, I do have a quality assurance CI job that does something similar.

fwiw: this is the output on the uncompressed CSV file.

```
$ python3 qa/block-timestamps/check-block-timestamps.py
Checking that timestamps don't deviate too much from block header timestamps
Imported 820249 timestamps from qa/block-timestamps/block-timestamps.csv
Checking timestamps.csv...
ERROR: Timestamp for block 726371 (000000000000000000083122d3fe07cc349dd200d497891411a711cdb49375f7) from source KIT Monitor B (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 38880.974s
ERROR: Timestamp for block 726370 (00000000000000000002684c0298ef3c6e4708e7d11b5f14a59b8137999ba279) from source KIT Monitor B (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 40210.373s
ERROR: Timestamp for block 691670 (0000000000000000000e6a6a0c859ab00b92c75d7e2a6643a530e5fc03cd5abc) from source KIT Monitor B (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 7259.312s
ERROR: Timestamp for block 691669 (00000000000000000000b88a682e96dd1c6b93be32c111f28b333783f46c8b19) from source KIT Monitor B (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 7418.312s
ERROR: Timestamp for block 691668 (0000000000000000000b6e1d7f0921a48618853d2d5979d8fa0c24d4831124c5) from source KIT Monitor B (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 7442.256s
ERROR: Timestamp for block 691667 (00000000000000000000fa50b1f2988a23d369a2ef560fcc2794c6892e1c4f4a) from source KIT Monitor B (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 7844.186s
ERROR: Timestamp for block 689623 (0000000000000000000761c150e65e8f17644a2185f36a355f1b472dbc1d53e9) from source KIT Monitor B (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 23523.359s
ERROR: Timestamp for block 689606 (00000000000000000012b2093e931ac9e62ab3a665625647cda72309f244f9e6) from source KIT Monitor B (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 34612.24s
ERROR: Timestamp for block 689597 (000000000000000000031d8f578807033b57cc3b8b73a7f7c1e91972ba1c826c) from source KIT Monitor B (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 40667.626s
ERROR: Timestamp for block 689595 (0000000000000000000e2224eba06fc8d376a057414d60fdffbbd95d3ba38672) from source KIT Monitor B (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 43161.31s
ERROR: Timestamp for block 689584 (00000000000000000006fd852fcf6a6377b9b979ac428476710115aa1b066daf) from source KIT Monitor B (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 47329.47s
ERROR: Timestamp for block 689540 (00000000000000000007ba54986a72067dac4730789d91b3b38b889c3bd8fdcb) from source KIT Monitor B (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 74067.925s
ERROR: Timestamp for block 689533 (000000000000000000108b7bd745c83190e7209e88d06ad7c09f3fe573bb4197) from source KIT Monitor B (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 80616.507s
ERROR: Timestamp for block 682344 (00000000000000000003e4c8f1c7bb96900057f352188680e7039dc9d059080f) from source KIT Monitor B (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 24558.592s
ERROR: Timestamp for block 682343 (0000000000000000000be4f9dcf52c3abf45eb6236fed804f0e714de4bde95ec) from source KIT Monitor B (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 25040.566s
ERROR: Timestamp for block 670641 (0000000000000000000cafae4b2f1a33ff770ec361366d1a52390eeaaeeeb23a) from source KIT Monitor B (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 46151.997s
ERROR: Timestamp for block 670640 (00000000000000000008966c80471cde133074acb5818dbc0432689a32c5474c) from source KIT Monitor B (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 46861.759s
ERROR: Timestamp for block 583136 (00000000000000000022b6c573a33a27fbb547e0668adff4d813896d98aeec5f) from source KIT Monitor B (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 116004.014s
ERROR: Timestamp for block 566938 (00000000000000000003e854aee7346a0d09d6ede68b3be8eb5ca0ff302cb72d) from source KIT Monitor 1 (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 39400.755s
ERROR: Timestamp for block 560469 (00000000000000000020a4ce87336fc0736a9965ff66cf9f3df5f561ebef9bdb) from source KIT Monitor 2 (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 7964.42s
ERROR: Timestamp for block 560468 (0000000000000000002a2ac2229355ad270d913191282c0a697321933ad51685) from source KIT Monitor 2 (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 7387.369s
ERROR: Timestamp for block 560467 (00000000000000000006b98777f7352c60465dfc3b387ff896291b247b9b6242) from source KIT Monitor 2 (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 7586.395s
ERROR: Timestamp for block 560466 (000000000000000000196d6d1d3f6fe9a9115a63d9b6714d9cef1a976bdb6b35) from source KIT Monitor 2 (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 9673.449s
ERROR: Timestamp for block 549741 (00000000000000000005da90b3f881e54016c0e4e35af45fdfdc0a542513aeb1) from source KIT Monitor 2 (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 28983.899s
ERROR: Timestamp for block 549714 (00000000000000000017bf87a77361c891edb479b15e21962b7f0ee2074342a9) from source KIT Monitor 2 (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 49048.837s
ERROR: Timestamp for block 495682 (0000000000000000001a5120a39b48f8b0b2f8566fc8e6e00084072bd76144a2) from source KIT Monitor 2 (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 16177.871s
ERROR: Timestamp for block 416413 (000000000000000004bcd22ace7ef21346865d2b27ba504ddf4ddd43a73102aa) from source KIT Monitor 1 (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 9609.54s
ERROR: Timestamp for block 416411 (000000000000000001caece62c012d54f5860f0c9d404c905f0b3903fa35558d) from source KIT Monitor 1 (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 10382.854s
ERROR: Timestamp for block 377774 (000000000000000004b314d46d33dce1fa1759b117330728704446ef65eabd72) from source KIT Monitor 1 (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 45760.332s
ERROR: Timestamp for block 377773 (000000000000000000d89d5ac3d2cd194de60fe13f8769f720ef6bcaf5f79dbe) from source KIT Monitor 1 (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 45985.703s
ERROR: Timestamp for block 377772 (00000000000000000ddc3b0303d8fc64c79e27b19ecd91054240b6932e31f94a) from source KIT Monitor 1 (dsn.kastel.kit.edu/bitcoin/) deviates more that 7200.0s into the future: 46450.491s

Statistics about offsets from block timestamps:
source                    count      min       max         mean        stdev       quantiles[s]
darosior node0            42639      -493s     2562s       20.76s      37.26s      [11.0, 20.0, 29.0]
0xB10C monitoring1        149105     -3440s    3665s       21.40s      30.11s      [10.645, 19.876, 29.128500000000003]
KIT Monitor B             239718     -3440s    116004s     24.30s      420.43s     [9.834, 19.266, 29.13225]
KIT Monitor 2             434909     -4418s    49049s      20.94s      111.95s     [9.662, 19.508, 30.299]
KIT Monitor 1             431282     -4418s    46450s      21.55s      156.33s     [9.647, 19.483, 30.265]
0xb10c memo               51491      -1708s    1442s       27.06s      45.43s      [11.0, 20.0, 30.0]
0xb10c memo-old           72693      -2130s    682s        20.90s      30.47s      [9.0, 19.0, 30.0]

Check not successful.
The listed timestamps might have been recorded during IBD or the system clock was wrong?
```

**Comment by matthias-g** [comment]
> fwiw: this is the output on the uncompressed CSV file.

Great, that's a helpful script!
I've used stricter rules for cleaning the data and have updated the commit.

**Comment by 0xB10C** [comment]
I split the big `timestamps.csv` file into one file per source (along with adding a script to combine them to one big `timestamps.csv` file again) as a result of #17 in #18. I've adopted your commit to the new format and pushed to https://github.com/bitcoin-data/block-arrival-times/tree/2023-12-kit-matthias-g. Let me know if the attribution in `data/README.md` is OK. Feel free to push this commit here or, alternatively, I'd be happy to open a new PR with it too.

**Comment by matthias-g** [comment]
Splitting the file per data source sounds like a good approach.
Your updates to the commit in https://github.com/bitcoin-data/block-arrival-times/tree/2023-12-kit-matthias-g look good. Thanks! I've copied the updated commit here.

**Comment by 0xB10C** [comment]
Thank you!

**Pull request merged**
